apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: vidaldocker/solar-system:85-ec90e3d846475b33590794d087b3d47a13a2a284
        name: solar-system
        ports: 
        - containerPort: 80
