apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: vidaldocker/solar-system:47-b89a672ed0c0f59ac6a3f5eaa8fb29b960ea93f3
        name: solar-system
        ports: 
        - containerPort: 80
