apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: vidaldocker/solar-system:101-4925f4dc5bbe5fdb3141ca89a2c6c62ce6e5d05d
        name: solar-system
        ports: 
        - containerPort: 80
