apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: vidaldocker/solar-system:57-c0690119dfd52a827142d2378fc9d2faccfc3d33
        name: solar-system
        ports: 
        - containerPort: 80
