apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: vidaldocker/solar-system:76-2b705f9daa2a9899c1406b06763f7b4eb5fc710a
        name: solar-system
        ports: 
        - containerPort: 80
