apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: vidaldocker/solar-system:207-3b47dbcf989cc0e21be8498e9736a9fd881aea6f
        name: solar-system
        ports: 
        - containerPort: 80
